"""Add missing columns to games table

Revision ID: 145e9c6a294a
Revises: 'c065e20230f5'
Create Date: 2025-06-11 18:11:38.914496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '145e9c6a294a'
down_revision = 'c065e20230f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass 
    # ### end Alembic commands ### 