"""Add missing columns to games table

Revision ID: 145e9c6a294a
Revises: 'c065e20230f5'
Create Date: 2025-06-11 18:11:38.914496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '145e9c6a294a'
down_revision = 'c065e20230f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS gametype CASCADE")
    op.execute("CREATE TYPE gametype AS ENUM('public', 'private')")

    # op.add_column('games', sa.Column('booking_id', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('game_type', sa.Enum('public', 'private', name='gametype'), nullable=False, server_default='private'))
    op.add_column('games', sa.Column('skill_level', sa.String(), nullable=True))
    
    # op.create_foreign_key(
    #     'fk_games_booking_id',
    #     'games', 'bookings',
    #     ['booking_id'], ['id']
    # )
    # op.create_unique_constraint('uq_games_booking_id', 'games', ['booking_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_games_booking_id', 'games', type_='unique')
    # op.drop_constraint('fk_games_booking_id', 'games', type_='foreignkey')
    op.drop_column('games', 'skill_level')
    op.drop_column('games', 'game_type')
    # op.drop_column('games', 'booking_id')
    
    op.execute("DROP TYPE IF EXISTS gametype CASCADE")
    # ### end Alembic commands ### 