"""Initial squashed migration

Revision ID: 27e9c9efe5f1
Revises: 
Create Date: 2025-06-15 21:18:37.028622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e9c9efe5f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('opening_time', sa.Time(), nullable=True))
    op.add_column('clubs', sa.Column('closing_time', sa.Time(), nullable=True))
    op.create_index(op.f('ix_elo_adjustment_requests_user_id'), 'elo_adjustment_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elo_adjustment_requests_user_id'), table_name='elo_adjustment_requests')
    op.drop_column('clubs', 'closing_time')
    op.drop_column('clubs', 'opening_time')
    # ### end Alembic commands ###
