"""Update court surface and status to enums

Revision ID: 860b6482a629
Revises: c1a9add3b8f7
Create Date: 2025-06-08 04:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from typing import Union, Sequence
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '860b6482a629'
down_revision: Union[str, None] = 'c1a9add3b8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE surfacetype ADD VALUE IF NOT EXISTS 'Turf'")
    op.execute("ALTER TYPE surfacetype ADD VALUE IF NOT EXISTS 'Hard Court'")
    op.execute("ALTER TYPE surfacetype ADD VALUE IF NOT EXISTS 'Sand'")
    op.execute("ALTER TYPE surfacetype ADD VALUE IF NOT EXISTS 'Clay'")
    op.execute("ALTER TYPE surfacetype ADD VALUE IF NOT EXISTS 'Hard'")
    op.execute("ALTER TYPE surfacetype ADD VALUE IF NOT EXISTS 'Grass'")
    op.execute("ALTER TYPE surfacetype ADD VALUE IF NOT EXISTS 'Artificial Grass'")
    op.execute("ALTER TYPE surfacetype ADD VALUE IF NOT EXISTS 'Artificial Grass Pro'")
    op.execute("ALTER TYPE surfacetype ADD VALUE IF NOT EXISTS 'Panoramic Glass'")
    op.execute("ALTER TYPE surfacetype ADD VALUE IF NOT EXISTS 'ConcreteTextured'")
    op.execute("ALTER TYPE surfacetype ADD VALUE IF NOT EXISTS 'Cushioned Hard Court'")
    
    court_availability_status = postgresql.ENUM('Available', 'Unavailable', 'Maintenance', name='courtavailabilitystatus')
    court_availability_status.create(op.get_bind(), checkfirst=True)

    op.alter_column('courts', 'surface_type',
               type_=sa.Enum('TURF', 'CLAY', 'HARD_COURT', 'SAND', name='surfacetype'),
               postgresql_using='surface_type::surfacetype')
    op.alter_column('courts', 'default_availability_status',
               type_=sa.Enum('AVAILABLE', 'UNAVAILABLE', 'MAINTENANCE', name='courtavailabilitystatus'),
               postgresql_using='default_availability_status::courtavailabilitystatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courts', 'default_availability_status',
               type_=sa.VARCHAR(),
               postgresql_using='default_availability_status::varchar')
    op.alter_column('courts', 'surface_type',
               type_=sa.VARCHAR(),
               postgresql_using='surface_type::varchar')
               
    court_availability_status = postgresql.ENUM('Available', 'Unavailable', 'Maintenance', name='courtavailabilitystatus')
    court_availability_status.drop(op.get_bind())

    surface_type = postgresql.ENUM('Turf', 'Clay', 'Hard Court', 'Sand', name='surfacetype')
    surface_type.drop(op.get_bind())
    # ### end Alembic commands ### 