"""Update court surface and status to enums

Revision ID: 860b6482a629
Revises: 'c1a9add3b8f7'
Create Date: 2025-06-08 12:03:58.620672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860b6482a629'
down_revision = 'c1a9add3b8f7'
branch_labels = 'None'
depends_on = 'None'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courts', 'surface_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('CLAY', 'HARD', 'GRASS', 'ARTIFICIAL_GRASS', name='surfacetype'),
               existing_nullable=True)
    op.alter_column('courts', 'default_availability_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('AVAILABLE', 'UNAVAILABLE', 'MAINTENANCE', name='courtavailabilitystatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courts', 'default_availability_status',
               existing_type=sa.Enum('AVAILABLE', 'UNAVAILABLE', 'MAINTENANCE', name='courtavailabilitystatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('courts', 'surface_type',
               existing_type=sa.Enum('CLAY', 'HARD', 'GRASS', 'ARTIFICIAL_GRASS', name='surfacetype'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ### 