"""Consolidate schema changes

Revision ID: 8b9379f6b454
Revises: '89a9b93cd5cb'
Create Date: 2025-06-14 12:18:27.625782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9379f6b454'
down_revision = '89a9b93cd5cb'
branch_labels = 'None'
depends_on = 'None'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_table('elo_adjustment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_rating', sa.Float(), nullable=False),
    sa.Column('requested_rating', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='eloadjustmentrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elo_adjustment_requests_id'), 'elo_adjustment_requests', ['id'], unique=False)
    op.create_table('team_players',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('games', sa.Column('team1_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('team2_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('winning_team_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('result_submitted', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'games', 'teams', ['team1_id'], ['id'])
    op.create_foreign_key(None, 'games', 'teams', ['winning_team_id'], ['id'])
    op.create_foreign_key(None, 'games', 'teams', ['team2_id'], ['id'])
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'result_submitted')
    op.drop_column('games', 'winning_team_id')
    op.drop_column('games', 'team2_id')
    op.drop_column('games', 'team1_id')
    op.drop_table('team_players')
    op.drop_index(op.f('ix_elo_adjustment_requests_id'), table_name='elo_adjustment_requests')
    op.drop_table('elo_adjustment_requests')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ### 